#!/bin/bash

function unificar_respuestas
{	
	AUXRESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")
	if [[ "$AUXRESPUESTA" = "ACEPTAR" || "$AUXRESPUESTA" = "" || "$AUXRESPUESTA" = "A" ]];then
		RESPUESTA="a"
	else
		if [[ "$AUXRESPUESTA" = "CANCELAR" || "$AUXRESPUESTA" = "C" ]];then
			RESPUESTA="c"
		else
			if [[ "$AUXRESPUESTA" = "VOLVER" || "$AUXRESPUESTA" = "V" ]];then
				RESPUESTA="v"
			fi
		fi
	fi
} 

function setParamFromConf
{
	getConfigParam "CURRDIR"
	GRUPO=$CONFIGPARAM	
	getConfigParam "BINDIR"	
	DEFBINDIR=$CONFIGPARAM
	getConfigParam "ARRIDIR"	
	DEFARRIDIR=$CONFIGPARAM
	getConfigParam "DATASIZE"	
	DEFDATASIZE=$CONFIGPARAM
	getConfigParam "LOGDIR"	
	DEFLOGDIR=$CONFIGPARAM
	getConfigParam "LOGEXT"	
	DEFLOGEXT=$CONFIGPARAM
	getConfigParam "MAXLOGSIZE"	
	DEFLOGSIZE=$CONFIGPARAM
}

function setParamDefault
{
	DEFBINDIR="/bin"
	DEFARRIDIR="/arribos"
	DEFDATASIZE="100"
	DEFLOGDIR="/log"
	DEFLOGEXT="log"
	DEFLOGSIZE="400"
	GRUPO=$(pwd)
	GRUPO="$GRUPO/$0"
	GRUPO=$(echo $GRUPO | sed -n "s/\(.*\)\(\/inst\/.*\)/\1/p")
}

function escapear_param
{
	ESCAPEADO=$(echo -e "$1" | sed "s/\//\\\\\//g")
}

function setear_conf_param
{
	escapear_param $2
	sed "s/\($1 = \)\(.*\)/\1$ESCAPEADO/" $GRUPO/conf/InstalarC.conf > $GRUPO/temp/InstalarC.conf
	mv $GRUPO/temp/InstalarC.conf $GRUPO/conf/InstalarC.conf
}

function actualizar_archivo_configuracion
{
	if [ -f "$GRUPO/conf/InstalarC.conf" ];then
		setear_conf_param "BINDIR" "$DEFBINDIR"
		setear_conf_param "ARRIDIR" "$DEFARRIDIR"
		setear_conf_param "DATASIZE" "$DEFDATASIZE Mb"
		setear_conf_param "LOGDIR" "$DEFLOGDIR"
		setear_conf_param "LOGEXT" "$DEFLOGEXT"
		setear_conf_param "MAXLOGSIZE" "$DEFLOGSIZE Kb"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/iniciarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/iniciarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "INICIARU" "$OWNER"
		setear_conf_param "INICIARF" "$FECHACREACION"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/detectarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/detectarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "DETECTARU" "$OWNER"
		setear_conf_param "DETECTARF" "$FECHACREACION"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/sumarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/sumarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "SUMARU" "$OWNER"
		setear_conf_param "SUMARF" "$FECHACREACION"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/listarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/listarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "LISTARU" "$OWNER"
		setear_conf_param "LISTARF" "$FECHACREACION"
	else	
		#echo -e "$GRUPO"
		echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$"
		echo -e "CURRDIR = $GRUPO" >> $GRUPO/conf/InstalarC.conf
		echo -e "CONFDIR = $GRUPO/conf" >> $GRUPO/conf/InstalarC.conf
		echo -e "DATAMAE = $GRUPO/mae" >> $GRUPO/conf/InstalarC.conf
		echo -e "LIBDIR = $GRUPO/lib" >> $GRUPO/conf/InstalarC.conf
		echo -e "BINDIR = $DEFBINDIR" >> $GRUPO/conf/InstalarC.conf
		echo -e "ARRIDIR = $DEFARRIDIR" >> $GRUPO/conf/InstalarC.conf
		echo -e "DATASIZE = $DEFDATASIZE Mb" >> $GRUPO/conf/InstalarC.conf
		echo -e "LOGDIR = $DEFLOGDIR" >> $GRUPO/conf/InstalarC.conf
		echo -e "LOGEXT = $DEFLOGEXT" >> $GRUPO/conf/InstalarC.conf
		echo -e "MAXLOGSIZE = $DEFLOGSIZE Kb" >> $GRUPO/conf/InstalarC.conf	
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/iniciarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/iniciarC "+%d/%m/%Y %k:%M:%S")
		echo -e "INICIARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "INICIARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/detectarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/detectarC "+%d/%m/%Y %k:%M:%S")
		echo -e "DETECTARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "DETECTARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/sumarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/sumarC "+%d/%m/%Y %k:%M:%S")
		echo -e "SUMARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "SUMARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/listarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/listarC "+%d/%m/%Y %k:%M:%S")
		echo -e "LISTARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "LISTARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		echo -e "reservada" >> $GRUPO/conf/InstalarC.conf
		echo -e "reservada" >> $GRUPO/conf/InstalarC.conf
	fi
}

function instalar_componente
{
	AUX=${INSTALADOS[$2]}
	if [ "$AUX" = "NO" ];then
		#echo -e "./$1"
		if [ -f "$GRUPO/inst/$1" ];then
			cp "$GRUPO/inst/$1" "$GRUPO$DEFBINDIR/$1" 
		else
			mostrar_grabar "Error en la instalacion, no se puede encontrar el archivo de comando $1" ES
			fin "cancelar"
		fi
	fi
}

function generar_directorios_archivos
{	
	#solo mostrar
	mostrar_grabar "Creando estructuras de Directorio......." I
	mkdir -p $GRUPO/conf
	mkdir -p $GRUPO/mae
	mkdir -p $GRUPO$DEFBINDIR
	mkdir -p $GRUPO$DEFARRIDIR
	mkdir -p $GRUPO$DEFLOGDIR
	mkdir -p $GRUPO/rechazados
	mkdir -p $GRUPO/preparados
	mkdir -p $GRUPO/listos
	mkdir -p $GRUPO/nolistos
	mkdir -p $GRUPO/ya
	mostrar_grabar "moviendo archivos...." I
	if [ -f "$GRUPO/inst/errores.mae" ];then
		cp "$GRUPO/inst/errores.mae" "$GRUPO/mae/errores.mae"
		cp "$GRUPO/inst/errores.mae" "$GRUPO/temp/errores.mae"		
	else
		mostrar_grabar "Error en la instalacion, no se puede encontrar el archivo errores.mae" I
		fin "cancelar"
	fi
	if [ -f "$GRUPO/inst/encuestas.mae" ];then
		cp "$GRUPO/inst/encuestas.mae" "$GRUPO/mae/encuestas.mae" 
	else
		mostrar_grabar "Advertencia en la instalacion, no se puede encontrar el archivo encuestas.mae" A
	fi
	if [ -f "$GRUPO/inst/preguntas.mae" ];then
		cp "$GRUPO/inst/preguntas.mae" "$GRUPO/mae/preguntas.mae" 
	else
		mostrar_grabar "Advertencia en la instalacion, no se puede encontrar el archivo preguntas.mae" A
	fi
	if [ -f "$GRUPO/inst/encuestadores.mae" ];then
		cp "$GRUPO/inst/encuestadores.mae" "$GRUPO/mae/encuestadores.mae" 
	else
		mostrar_grabar "Advertencia en la instalacion, no se puede encontrar el archivo encuestadores.mae" A
	fi
	instalar_componente "iniciarC" 1
	instalar_componente "detectarC" 2
	instalar_componente "sumarC" 3
	instalar_componente "listarC" 4
}

function configurar_logsize
{
	mostrar_grabar "Ingrese el tamaño maximo para los archivos $DEFLOGEXT (en Kbytes): $DEFLOGSIZE" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^[0-9][0-9]*$");		
		if [ "$VALIDACION" != "" ];then
			DEFLOGSIZE=$RESPUESTA
		else
			mostrar_grabar "error en la data ingresada, se esperaba un numero entero" I;		
			configurar_logsize		
		fi		
	fi
}

function configurar_logext
{
	mostrar_grabar "Ingrese la extensión para los archivos de log: (.$DEFLOGEXT)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^\.[a-zA-Z0-9][a-zA-Z0-9]*\(\.[a-zA-Z0-9][a-zA-Z0-9]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			DEFLOGEXT=$(echo "$RESPUESTA" | sed -n "s/\.\(.*\)/\1/p")	
			#DEFLOGEXT=$RESPUESTA
		else
			mostrar_grabar "error en el formato de extension ingresado, se espera empiece con punto y termine con digitos" I;		
			configurar_logext		
		fi	
	fi
}


function configurar_logdir
{
	mostrar_grabar "Ingrese el nombre del directorio de log: ($GRUPO$DEFLOGDIR)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			DEFLOGDIR=$RESPUESTA
		else
			mostrar_grabar "error en el armado del path, debe arrancar con / y terminar con digito, numero o _" I;		
			configurar_logdir		
		fi		
		
	fi
}


function configurar_bindir
{
	mostrar_grabar "Ingrese el nombre del subdirectorio de ejecutables: ($GRUPO$DEFBINDIR)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			DEFBINDIR=$RESPUESTA
		else
			mostrar_grabar "error en el armado del path, debe arrancar con / y terminar con digito, numero o _" I;		
			configurar_bindir		
		fi	
		
	fi
}

function chequear_espacio_disco
{
	ESPACIOLIBRE=$(df -h | sed -n "s/\([^ ]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9,\.][0-9,\.]*\)\([GKMB]\)\(.*\)\/$/\7/p")
	UNIDAD=$(df -h | sed -n "s/\([^ ]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9,\.][0-9,\.]*\)\([GKMB]\)\(.*\)\/$/\8/p")	
	HAYCOMA=$(echo "$ESPACIOLIBRE" | grep ".*,.*")
	if [ "$HAYCOMA" != "" ];then
		ESPACIOLIBRE=$(echo "$ESPACIOLIBRE" | sed -n "s/\(.*\)\(,\)\(.*\)/\1.\3/p")
	fi
	case "$UNIDAD" in
		"G")
			ESPACIOLIBRE=$(echo "($ESPACIOLIBRE*1024)/1" | bc)
		;;
		"M")
			ESPACIOLIBRE=$ESPACIOLIBRE
		;;
		"K")
			ESPACIOLIBRE=$(echo "($ESPACIOLIBRE/1024)/1" | bc)
		;;
		"B")
			ESPACIOLIBRE=$(echo "($ESPACIOLIBRE*1048576)/1" | bc)
		;;
	esac
	HAYESPACIOLIBRE="SI"
	if [ $ESPACIOLIBRE -le $DEFDATASIZE ];then
		HAYESPACIOLIBRE="NO"
	fi

} 

function configurar_datasize
{
	mostrar_grabar "Ingrese el espacio mínimo requerido para datos externos(en Mbytes):" I
	mostrar_grabar "$DEFDATASIZE Mb" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^[0-9][0-9]*$");		
		if [ "$VALIDACION" != "" ];then
			DEFDATASIZE=$RESPUESTA
		else
			mostrar_grabar "error en la data ingresada, se esperaba un numero entero" I;		
			configurar_datasize		
		fi
	fi
}

function configurar_arridir
{
	mostrar_grabar "Ingrese el nombre del directorio que permite el arribo de archivos" I
	mostrar_grabar "externos ($GRUPO$DEFARRIDIR)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			DEFARRIDIR=$RESPUESTA
		else
			mostrar_grabar "error en el armado del path, debe arrancar con / y terminar con digito, numero o _" I;		
			configurar_arridir		
		fi		

	fi
}

function configurar_instalacion
{
	#falta log de las respuestas
	configurar_arridir
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		HAYESPACIOLIBRE="NO"
		while [[ "$HAYESPACIOLIBRE" = "NO" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];do
			configurar_datasize
			if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
				chequear_espacio_disco
				if [ "$HAYESPACIOLIBRE" = "NO" ];then		
				mostrar_grabar "Insuficiente espacio en disco. Espacio disponible: $ESPACIOLIBRE Mb." I
				mostrar_grabar "Espacio requerido $DEFDATASIZE Mb" I	
				DEFDATASIZE="100"		
				fi
			fi
		done
	fi
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_bindir
	fi	
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_logdir
	fi
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_logext
	fi
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_logsize
	fi
	if [ "$RESPUESTA" = "c" ];then
		fin "cancelar"
	fi
	if [ "$RESPUESTA" = "v" ];then
		configurar_instalacion
	fi
	
}

function fin
{
	#cerrar el InstalarC.log
	if [ "$#" = "1" ];then
		if [ "$1" = "cancelar" ];then
			mostrar_grabar "Proceso de instalación cancelado" I
		fi
	fi
	rm -fr $GRUPO/temp
	exit 0
}

function mostrar_grabar
{	
	#si no se pasa $3, se muestra por pantalla y loguea. Si $3=G solo loguea, sino solo muestra por pantalla
	#$2 tipo de mensaje
	#$1 mensaje
	if [ "$#" = 3 ];then
		if [ "$3" = "G" ];then
			"$LIBDIR"/loguearC "InstalarC" "$2" "$1"
		else
			echo -e "$1"
		fi
	else	
		"$LIBDIR"/loguearC "InstalarC" "$2" "$1"
		echo -e "$1"
	fi
}

function instalacion_parcial
{
	mostrar_grabar "Se propone la instalación de los componentes faltantes, con las variables de instalación" I
	mostrar_grabar "siguientes, predefinidas en el archivo de configuración : " I
	AUXCAT=$(cat "$GRUPO/conf/InstalarC.conf")
	mostrar_grabar "$AUXCAT" I
	mostrar_grabar "¿acepta completar la instalación?(Si/No)" I
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	RESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")		
	if [ "$RESPUESTA" = "SI" ];then
		setParamFromConf
		generar_directorios_archivos
		actualizar_archivo_configuracion
		verificar_instalacion
		print_instalacion_parcial
		mostrar_grabar "* FIN del proceso de Instalación Copyright SisOp (c)2011	*" I
		mostrar_grabar "*****************************************************************" I
	else
		mostrar_grabar "¿desea iniciar una instalación completa nueva?(Si/No)" I
		read -e RESPUESTA	
		mostrar_grabar "$RESPUESTA" I G
		RESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")		
		if [ "$RESPUESTA" = "SI" ];then
			INSTALADOS[1]="NO"
			INSTALADOS[2]="NO"
			INSTALADOS[3]="NO"
			INSTALADOS[4]="NO"
			setParamDefault
			instalacion_completa
		else
			fin "cancelar"
		fi	
	fi
}

function instalacion_completa
{		
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*      Sistema Consultar Copyright SisOp (c)2011       *' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*Al instalar Consultar UD. expresa estar en un todo de acuerdo *' I
	mostrar_grabar '*con los términos y condiciones del \"ACUERDO DE LICENCIA DE *' I
	mostrar_grabar '*SOFTWARE \" incluido en este paquete.' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar 'Aceptar/Rechazar(a/r)' I
	RESPUESTA="";	
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [ "$RESPUESTA" = "a" ];then	
		PERL=$(perl --version | sed -n "s/\(.*v\)\([5-9]\.[0-9.]*\)\(.*\)/\2/p")	
		if [ "$PERL" = "" ];then
			mostrar_grabar "Para instalar Consultar es necesario contar con Perl 5 o superior" I
			mostrar_grabar "intalado. Efectúe su instalación e inténtelo nuevamente. Proceso de" I
			mostrar_grabar "Instalación Cancelado" I
		else
			mostrar_grabar "La version de perl instalada en el sistema es v$PERL" I
			mostrar_grabar "Todos los directorios del sistema serán subdirectorios de $GRUPO" I
			mostrar_grabar "Todos los componentes de la instalación se obtendrán del repositorio:" I
			mostrar_grabar "$GRUPO/inst" I
			AUXLISTADO=$(ls "$GRUPO/inst")			
			mostrar_grabar "$AUXLISTADO" I
			mostrar_grabar "El log de la instalacion se almacenara en $GRUPO/inst" I
			mostrar_grabar "Al finalizar la instalación, si la misma fue exitosa se dejara un" I
 			mostrar_grabar "archivo de configuración en $GRUPO/conf" I
			while [ "1" = "1" ]; do
				configurar_instalacion
				clear
				mostrar_grabar  "****************************************************************" I
				mostrar_grabar  "*" I
				mostrar_grabar  "*	Parámetros de instalación del paquete Consultar		*" I
				mostrar_grabar  "****************************************************************" I
				mostrar_grabar  "*" I
				mostrar_grabar  "Directorio de trabajo: $GRUPO" I
				mostrar_grabar  "Directorio de instalación: $GRUPO/inst" I
				mostrar_grabar  "Directorio de configuración: $GRUPO/conf" I
				mostrar_grabar  "Directorio de datos maestros: $GRUPO/mae" I
				mostrar_grabar  "Directorio de ejecutables: $DEFBINDIR" I
				mostrar_grabar  "Librería de funciones: $GRUPO/lib" I
				mostrar_grabar	"Directorio de arribos: $DEFARRIDIR" I
				mostrar_grabar	"Espacio mínimo reservado en $ARRIDIR: $DEFDATASIZE MB" I
				mostrar_grabar  "Directorio para los archivos de Log: $DEFLOGDIR" I
				mostrar_grabar  "Extensión para los archivos de Log: $DEFLOGEXT" I
				mostrar_grabar  "Tamaño máximo para los archivos de Log: $DEFLOGSIZE KB" I
				mostrar_grabar  "Log de la instalación: $GRUPO/inst" I
				mostrar_grabar  "Si los datos ingresados son correctos de ENTER para continuar, si" I
				mostrar_grabar	"desea modificar algún parámetro oprima cualquier tecla para reiniciar" I
				#si toca cualquier tecla que no sea tab,enter o space
				read -d '' -sn1 RESPUESTA
				if [ "$RESPUESTA" = "" ];then
					mostrar_grabar "se presiono enter" I G
					break
				else
					mostrar_grabar "$RESPUESTA" I G					
					clear
				fi
			done
			mostrar_grabar "Iniciando Instalación... Está UD. seguro? (Si/No)" I			
			read -e RESPUESTA	
			mostrar_grabar "$RESPUESTA" I G
			RESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")		
			if [ "$RESPUESTA" != "SI" ];then
				fin "cancelar"
			fi
			generar_directorios_archivos
			actualizar_archivo_configuracion
			verificar_instalacion
			print_instalacion_parcial
			mostrar_grabar "* FIN del proceso de Instalación Copyright SisOp (c)2011	*" I
			mostrar_grabar "*****************************************************************" I	
		fi
	else
		fin "cancelar"
	fi
}

function print_instalacion_completa
{
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*      Sistema Consultar Copyright SisOp (c)2011       *' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*Se encuentran instalados los siguientes componentes:  *' I
	mostrar_grabar "$MENSAJESI" I
	mostrar_grabar '********************************************************' I
	mostrar_grabar 'Proceso de instalacion cancelado' I
}

function print_instalacion_parcial
{
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*      Sistema Consultar Copyright SisOp (c)2011       *' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*Se encuentran instalados los siguientes componentes:  *' I
	mostrar_grabar "$MENSAJESI" I
	mostrar_grabar '*Falta instalar los siguientes componentes:            *' I
	mostrar_grabar "$MENSAJENO" I
	mostrar_grabar '********************************************************' I
}

function comando_instalado
{
	
	if [ -f $1 ];then
		OWNER=$(stat -c %U "$1")
		FECHACREACION=$(date -r $1 "+%d/%m/%Y %k:%M:%S")
		INSTALADOS[$3]="SI"
		MENSAJESI="$MENSAJESI\n*$2 $FECHACREACION $OWNER*"
	else
		INSTALACION="parcial"
		INSTALADOS[$3]="NO"
		MENSAJENO="$MENSAJENO\n*$2"
	fi 
}
function verificar_instalacion
{
#1iniciarC
#2detectarC
#3sumarC
#4listarC
FILE="$GRUPO/conf/InstalarC.conf"
INSTALADOS[1]="NO"
INSTALADOS[2]="NO"
INSTALADOS[3]="NO"
INSTALADOS[4]="NO"
if [ -f $FILE ];then
	INSTALACION="completa"
	MENSAJESI=""
	MENSAJENO=""
	#se verifica esten instalados los comandos en bin
	getConfigParam "BINDIR"
	PATHAUX="$GRUPO$CONFIGPARAM/iniciarC"
	comando_instalado $PATHAUX "iniciarC" 1
	PATHAUX="$GRUPO$CONFIGPARAM/detectarC"
	comando_instalado $PATHAUX "detectarC"	2
	PATHAUX="$GRUPO$CONFIGPARAM/sumarC"
	comando_instalado $PATHAUX "sumarC" 3	
	PATHAUX="$GRUPO$CONFIGPARAM/listarC"
	comando_instalado $PATHAUX "listarC" 4	
	if [ "$MENSAJESI" = "" ];then
		INSTALACION="ninguna"
	fi

else 
	INSTALACION="ninguna"
fi
}
function getConfigParam
{
	CONFIGPARAM=$(sed -n "s/$1 = //p" $GRUPO/conf/InstalarC.conf)
}

GRUPO=$(pwd)
GRUPO="$GRUPO/$0"
GRUPO=$(echo $GRUPO | sed -n "s/\(.*\)\(\/inst\/.*\)/\1/p")
LIBDIR="$GRUPO/lib"
PATH=${PATH}:$LIBDIR
DATAMAE=$GRUPO/temp
mkdir -p $GRUPO/temp
#GRUPO=${GRUPO%/*}
export GRUPO
export LOGSIZE=400000
export LOGEXT=log
export LOGDIR="$GRUPO/inst"
export PATH
export DATAMAE
chmod 777 "$LIBDIR"/*
DATE=$(date "+%d/%m/%Y %k:%M:%S")
mostrar_grabar "$DATE-$USERNAME-instalarC-I-Inicio de ejecucion" I G
verificar_instalacion
case "$INSTALACION" in
	"completa")
		print_instalacion_completa
		;;
	"parcial")
		print_instalacion_parcial
		instalacion_parcial
		;;
	"ninguna")
		if [ -f $GRUPO/conf/InstalarC.conf ];then
			setParamFromConf	
		else
			setParamDefault
		fi
		instalacion_completa
		;;
esac
fin

