#!/bin/bash

#Variables principales

#GRUPO
#DEFBINDIR
#DEFARRIDIR
#DEFDATASIZE
#DEFLOGDIR
#DEFLOGEXT
#DEFLOGSIZE
#MENSAJESI se van concatenando los comandos instalados con su informacion
#MENSAJENO se van concatenando los comandos no instalados
#RESPUESTA donde se almacena la ultima respuesta ingresada por teclado
#INSTALADOS arreglo donde queda indicado para cada comando si el mismo esta instalado
#		1 iniciarC
#		2 detectarC
#		3 sumarC
#		4 listarC

#********muestra por pantalla la información de ayuda del InstalarC
mostrarAyuda() {
	echo
	echo "Realiza la instalacion del paquete Consultar, creando las estructuras de directorios y archivos, segun las especificaciones del usuario"
	echo
	echo "MODO DE USO: InstalarC [OPCION]"	
	echo
	echo "OPCIONES:"
	echo "-h, --help    Muestra esta pantalla"
	echo "-v, --version    Informa acerca de la version"
	echo
	echo "EJEMPLOS:"
	echo
	echo -e "InstalarC"
	echo -e "Realiza la instalacion del paquete Consultar"
	echo 
	echo -e "InstalarC -h"
	echo -e "muestra la pantalla de ayuda del Instalarc"
	echo
	echo -e "InstalarC -v"
	echo -e "muestra la información de la version del InstalarC"
	echo
return 0
}

#*******Dada distintas respuesta posibles ingresada por el usuario y con un mismo significado, se las unifica para ser #*******tratadas de igual manera   
function unificar_respuestas
{	
	AUXRESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")
	if [[ "$AUXRESPUESTA" = "ACEPTAR" || "$AUXRESPUESTA" = "" || "$AUXRESPUESTA" = "A" ]];then
		RESPUESTA="a"
	else
		if [[ "$AUXRESPUESTA" = "CANCELAR" || "$AUXRESPUESTA" = "C" ]];then
			RESPUESTA="c"
		else
			if [[ "$AUXRESPUESTA" = "VOLVER" || "$AUXRESPUESTA" = "V" ]];then
				RESPUESTA="v"
			fi
		fi
	fi
} 

#*******Se setean los parametros de configuración default desde el archivo InstalarC.conf
function setParamFromConf
{
	getConfigParam "CURRDIR"
	GRUPO=$CONFIGPARAM	
	getConfigParam "BINDIR"	
	DEFBINDIR=$CONFIGPARAM
	getConfigParam "ARRIDIR"	
	DEFARRIDIR=$CONFIGPARAM
	getConfigParam "DATASIZE"	
	DEFDATASIZE=$CONFIGPARAM
	getConfigParam "LOGDIR"	
	DEFLOGDIR=$CONFIGPARAM
	getConfigParam "LOGEXT"	
	DEFLOGEXT=$CONFIGPARAM
	getConfigParam "MAXLOGSIZE"	
	DEFLOGSIZE=$CONFIGPARAM
}

#*******Se setean los parametros de configuración default con constantes default
function setParamDefault
{
	DEFBINDIR="/bin"
	DEFARRIDIR="/arribos"
	DEFDATASIZE="100"
	DEFLOGDIR="/log"
	DEFLOGEXT="log"
	DEFLOGSIZE="400"
	GRUPO=$(pwd)
	GRUPO="$GRUPO/$0"
	GRUPO=$(echo $GRUPO | sed -n "s/\(.*\)\(\/inst\/.*\)/\1/p")
}

#*******Dada una expresion pasada por parametros se le escapea /, reemplazandola por \/
#*******$1 es la expresion a escapear
function escapear_param
{
	ESCAPEADO=$(echo -e "$1" | sed "s/\//\\\\\//g")
}

#*******Dada el nombre de una variable($1) y un nuevo valor($2),se cambia el valor existente de dicha variable en el #*******InstalarC.conf por el nuevo valor
#*******$1 nombre de la variable a cambiar
#*******$2 nuevo valor de la variable a cambiar
function setear_conf_param
{
	escapear_param $2
	sed "s/\($1 = \)\(.*\)/\1$ESCAPEADO/" $GRUPO/conf/InstalarC.conf > $GRUPO/temp/InstalarC.conf
	mv $GRUPO/temp/InstalarC.conf $GRUPO/conf/InstalarC.conf
}

#*******Se crea o actualiza el archivo de configuración InstalarC.conf, con los nuevos valores default
function actualizar_archivo_configuracion
{	
#*******Si el archivo de configuración InstalarC.conf existe, se setean todos los parametros con los nuevos valores, uno a #*******la vez
	if [ -f "$GRUPO/conf/InstalarC.conf" ];then
		setear_conf_param "BINDIR" "$DEFBINDIR"
		setear_conf_param "ARRIDIR" "$DEFARRIDIR"
		setear_conf_param "DATASIZE" "$DEFDATASIZE Mb"
		setear_conf_param "LOGDIR" "$DEFLOGDIR"
		setear_conf_param "LOGEXT" "$DEFLOGEXT"
		setear_conf_param "MAXLOGSIZE" "$DEFLOGSIZE Kb"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/iniciarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/iniciarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "INICIARU" "$OWNER"
		setear_conf_param "INICIARF" "$FECHACREACION"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/detectarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/detectarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "DETECTARU" "$OWNER"
		setear_conf_param "DETECTARF" "$FECHACREACION"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/sumarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/sumarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "SUMARU" "$OWNER"
		setear_conf_param "SUMARF" "$FECHACREACION"
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/listarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/listarC "+%d/%m/%Y %k:%M:%S")
		setear_conf_param "LISTARU" "$OWNER"
		setear_conf_param "LISTARF" "$FECHACREACION"
	else	
#*******Si el archivo de configuración InstalarC.conf no existe, se lo crea con los nuevos valores default
		#echo -e "$GRUPO"
		echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$"
		echo -e "CURRDIR = $GRUPO" >> $GRUPO/conf/InstalarC.conf
		echo -e "CONFDIR = $GRUPO/conf" >> $GRUPO/conf/InstalarC.conf
		echo -e "DATAMAE = $GRUPO/mae" >> $GRUPO/conf/InstalarC.conf
		echo -e "LIBDIR = $GRUPO/lib" >> $GRUPO/conf/InstalarC.conf
		echo -e "BINDIR = $DEFBINDIR" >> $GRUPO/conf/InstalarC.conf
		echo -e "ARRIDIR = $DEFARRIDIR" >> $GRUPO/conf/InstalarC.conf
		echo -e "DATASIZE = $DEFDATASIZE Mb" >> $GRUPO/conf/InstalarC.conf
		echo -e "LOGDIR = $DEFLOGDIR" >> $GRUPO/conf/InstalarC.conf
		echo -e "LOGEXT = $DEFLOGEXT" >> $GRUPO/conf/InstalarC.conf
		echo -e "MAXLOGSIZE = $DEFLOGSIZE Kb" >> $GRUPO/conf/InstalarC.conf	
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/iniciarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/iniciarC "+%d/%m/%Y %k:%M:%S")
		echo -e "INICIARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "INICIARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/detectarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/detectarC "+%d/%m/%Y %k:%M:%S")
		echo -e "DETECTARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "DETECTARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/sumarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/sumarC "+%d/%m/%Y %k:%M:%S")
		echo -e "SUMARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "SUMARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		OWNER=$(stat -c %U $GRUPO$DEFBINDIR/listarC)
		FECHACREACION=$(date -r $GRUPO$DEFBINDIR/listarC "+%d/%m/%Y %k:%M:%S")
		echo -e "LISTARU = $OWNER" >> $GRUPO/conf/InstalarC.conf
		echo -e "LISTARF = $FECHACREACION" >> $GRUPO/conf/InstalarC.conf
		echo -e "reservada" >> $GRUPO/conf/InstalarC.conf
		echo -e "reservada" >> $GRUPO/conf/InstalarC.conf
	fi
}

#*******Instala el componente pasado por parametros
#*******$1 nombre del comando a instalar
#*******$2 indice del comando en INSTALADOS
function instalar_componente
{
#********Verifica si el comando a Instalar no fue ya instalado, y solo instala si es necesario
	AUX=${INSTALADOS[$2]}
	if [ "$AUX" = "NO" ];then 
		#echo -e "./$1"
		if [ -f "$GRUPO/inst/$1" ];then
			cp "$GRUPO/inst/$1" "$GRUPO$DEFBINDIR/$1" 
		else
			mostrar_grabar "Error severo en la instalacion, no se puede encontrar el archivo de comando $1. Instalación corrompida, consulte a su proveedor" ES
			fin "cancelar"
		fi
	fi
}

#*******Crea los directorios segun las variables default, y copia los archivos de la carpeta inst a las carpetas #*******correspondientes
function generar_directorios_archivos
{	
	#solo mostrar
	mostrar_grabar "Creando estructuras de Directorio......." I
	mkdir -p $GRUPO/conf
	mkdir -p $GRUPO/mae
	mkdir -p $GRUPO$DEFBINDIR
	mkdir -p $GRUPO$DEFARRIDIR
	mkdir -p $GRUPO$DEFLOGDIR
	mkdir -p $GRUPO/rechazados
	mkdir -p $GRUPO/preparados
	mkdir -p $GRUPO/listos
	mkdir -p $GRUPO/nolistos
	mkdir -p $GRUPO/ya
	mostrar_grabar "moviendo archivos...." I
	cp "$GRUPO/inst/errores.mae" "$GRUPO/mae/errores.mae"
	#********Previo a mover cualquier archivo desde inst se chequea su existencia, informando su ausencia de ser 		#*******necesario
	if [ -f "$GRUPO/inst/encuestas.mae" ];then
		cp "$GRUPO/inst/encuestas.mae" "$GRUPO/mae/encuestas.mae" 
	else
		mostrar_grabar "Advertencia en la instalacion, no se puede encontrar el archivo encuestas.mae" A
	fi
	if [ -f "$GRUPO/inst/preguntas.mae" ];then
		cp "$GRUPO/inst/preguntas.mae" "$GRUPO/mae/preguntas.mae" 
	else
		mostrar_grabar "Advertencia en la instalacion, no se puede encontrar el archivo preguntas.mae" A
	fi
	if [ -f "$GRUPO/inst/encuestadores.mae" ];then
		cp "$GRUPO/inst/encuestadores.mae" "$GRUPO/mae/encuestadores.mae" 
	else
		mostrar_grabar "Advertencia en la instalacion, no se puede encontrar el archivo encuestadores.mae" A
	fi
	instalar_componente "iniciarC" 1
	instalar_componente "detectarC" 2
	instalar_componente "sumarC" 3
	instalar_componente "listarC" 4
}

#*******Se pide y se setea, segun lo ingresado por teclado, el nuevo tamaño maximo del archivo del log
function configurar_logsize
{
#*******Se pide por pantalla que se setee el tamaño maximo de los archivos de log 
	mostrar_grabar "Ingrese el tamaño maximo para los archivos $DEFLOGEXT (en Kbytes): $DEFLOGSIZE" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	#*******Solo si la respuesta no es ni aceptar, ni cancelar, ni volver se setea el nuevo valor de tamaño
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		#*******se verifica que el valor ingresado por teclado sea un numero entero
		VALIDACION=$(echo "$RESPUESTA" | grep "^[0-9][0-9]*$");		
		if [ "$VALIDACION" != "" ];then
			#********se cambia el valor default si el ingresado por teclado resulta valido
			DEFLOGSIZE=$RESPUESTA
		else
			mostrar_grabar "error en la data ingresada, se esperaba un numero entero" I;		
			configurar_logsize		
		fi		
	fi
}

#*******Se pide y se setea, segun lo ingresado por teclado, la nueva extension de los archivos de log
function configurar_logext
{
#*******Se pide por pantalla que se setee la nueva extension para los archivos de log 
	mostrar_grabar "Ingrese la extensión para los archivos de log: (.$DEFLOGEXT)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	#*******Solo si la respuesta no es ni aceptar, ni cancelar, ni volver se setea el nuevo valor de extension de log
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		#*******se verifica que el valor ingresado por teclado empiece con punto, y termine con caracter 			#*******alfa-numerico
		VALIDACION=$(echo "$RESPUESTA" | grep "^\.[a-zA-Z0-9][a-zA-Z0-9]*\(\.[a-zA-Z0-9][a-zA-Z0-9]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			#********se cambia el valor default si el ingresado por teclado resulta valido			
			DEFLOGEXT=$(echo "$RESPUESTA" | sed -n "s/\.\(.*\)/\1/p")	
			#DEFLOGEXT=$RESPUESTA
		else
			mostrar_grabar "error en el formato de extension ingresado, se espera empiece con punto y termine con caracter alfa-numerico" I;	
			configurar_logext		
		fi	
	fi
}
#*******Se pide y se setea, segun lo ingresado por teclado, el nuevo directorio de los archivos de log
function configurar_logdir
{
	mostrar_grabar "Ingrese el nombre del directorio de log: ($GRUPO$DEFLOGDIR)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			DEFLOGDIR=$RESPUESTA
		else
			mostrar_grabar "error en el armado del path, debe arrancar con / y terminar con un caracter alfa-numerico o _" I;		
			configurar_logdir		
		fi		
		
	fi
}
#*******Se pide y se setea, segun lo ingresado por teclado, el nuevo directorio de los archivos ejecutables
function configurar_bindir
{
	mostrar_grabar "Ingrese el nombre del subdirectorio de ejecutables: ($GRUPO$DEFBINDIR)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			DEFBINDIR=$RESPUESTA
		else
			mostrar_grabar "error en el armado del path, debe arrancar con / y terminar con un caracter alfa-numerico o _" I;
			configurar_bindir		
		fi	
		
	fi
}

#*******Verifica si el espacio libre en disco alcanza para el espacio necesitado en la variable $DEFDATASIZE
#*******$DEFDATASIZE contiene el tamaño de espacio en disco que se quiere verificar si se dispone
#*******$ESPACIOLIBRE se retorna el espacio total de disco del que se dispone en megas
#*******$HAYESPACIOLIBRE retorna el valor de la verificacion. "Si", en caso de que exista espacio suficiente en disco, y #*******		"No" en caso contrario
function chequear_espacio_disco
{
#*******Se obtiene el espacio disponible en disco y la unidad 
	ESPACIOLIBRE=$(df -h | sed -n "s/\([^ ]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9,\.][0-9,\.]*\)\([GKMB]\)\(.*\)\/$/\7/p")
	UNIDAD=$(df -h | sed -n "s/\([^ ]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9GKMB,\.][0-9GKMB,\.]*\)\([ ]*\)\([0-9,\.][0-9,\.]*\)\([GKMB]\)\(.*\)\/$/\8/p")	
	#*******Si hay una coma en el numero, se reemplaza la misma por punto, ya que bc soporta punto y no coma
	HAYCOMA=$(echo "$ESPACIOLIBRE" | grep ".*,.*")
	if [ "$HAYCOMA" != "" ];then
		ESPACIOLIBRE=$(echo "$ESPACIOLIBRE" | sed -n "s/\(.*\)\(,\)\(.*\)/\1.\3/p")
	fi
	#*******Segun la unidad, se hace el pasaje del ESPACIOLIBRE a megas y se redondea para abajo
	case "$UNIDAD" in
		"G")
			ESPACIOLIBRE=$(echo "($ESPACIOLIBRE*1024)/1" | bc)
		;;
		"M")
			ESPACIOLIBRE=$ESPACIOLIBRE
		;;
		"K")
			ESPACIOLIBRE=$(echo "($ESPACIOLIBRE/1024)/1" | bc)
		;;
		"B")
			ESPACIOLIBRE=$(echo "($ESPACIOLIBRE*1048576)/1" | bc)
		;;
	esac
	#*******Se verifica si se dispone de suficiente espacio libre en el disco
	HAYESPACIOLIBRE="SI"
	if [ $ESPACIOLIBRE -le $DEFDATASIZE ];then
		HAYESPACIOLIBRE="NO"
	fi

} 
#*******Se pide y se setea, segun lo ingresado por teclado, el nuevo tamaño minimo que se debe disponer para datos externos
function configurar_datasize
{
	mostrar_grabar "Ingrese el espacio mínimo requerido para datos externos(en Mbytes):" I
	mostrar_grabar "$DEFDATASIZE Mb" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^[0-9][0-9]*$");		
		if [ "$VALIDACION" != "" ];then
			DEFDATASIZE=$RESPUESTA
		else
			mostrar_grabar "error en la data ingresada, se esperaba un numero entero" I;		
			configurar_datasize		
		fi
	fi
}
#*******Se pide y se setea, segun lo ingresado por teclado, el nuevo directorio de los archivos de arribos
function configurar_arridir
{
	mostrar_grabar "Ingrese el nombre del directorio que permite el arribo de archivos" I
	mostrar_grabar "externos ($GRUPO$DEFARRIDIR)" I
	#opciones aceptar,cancelar,volver y opcion nueva
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [[ "$RESPUESTA" != "a" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		VALIDACION=$(echo "$RESPUESTA" | grep "^\/[a-zA-Z0-9_][a-zA-Z0-9_]*\(\/[a-zA-Z0-9_][a-zA-Z0-9_]*\)*$");		
		if [ "$VALIDACION" != "" ];then
			DEFARRIDIR=$RESPUESTA
		else
			mostrar_grabar "error en el armado del path, debe arrancar con / y terminar con un caracter alfa-numerico o _" I;
			configurar_arridir		
		fi		

	fi
}

#*******Se setean todos los parametros de configuración de instalación por parte del usuario
#*******$RESPUESTA queda registrada la ultima respuesta ingresada por parte del usuario
#*******
function configurar_instalacion
{
	configurar_arridir
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
		HAYESPACIOLIBRE="NO"
		while [[ "$HAYESPACIOLIBRE" = "NO" && "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];do
			configurar_datasize
			if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then
				chequear_espacio_disco
				if [ "$HAYESPACIOLIBRE" = "NO" ];then		
				mostrar_grabar "Insuficiente espacio en disco. Espacio disponible: $ESPACIOLIBRE Mb." I
				mostrar_grabar "Espacio requerido $DEFDATASIZE Mb" I	
				DEFDATASIZE="100"		
				fi
			fi
		done
	fi
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_bindir
	fi	
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_logdir
	fi
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_logext
	fi
	if [[ "$RESPUESTA" != "c" && "$RESPUESTA" != "v" ]];then		
		configurar_logsize
	fi
	#*******si se ingreso c de cancelar, se llama a la finalizacion del InstalarC
	if [ "$RESPUESTA" = "c" ];then
		fin "cancelar"
	fi
	#*******si se ingreso v de volver, se vuelve a invocar el configurar_instalacion para empezar nuevamente el seteo 		#*******de parametros, con los valores default modificados hasta el parametro donde se ingreso volver.
	if [ "$RESPUESTA" = "v" ];then
		configurar_instalacion
	fi
	
}

#*******Finaliza la ejecucion del comando InstalarC
function fin
{	
	#*******Si se paso como primer parametro "cancelar", muestra por pantalla y por log dicha cancelación
	#cerrar el InstalarC.log
	if [ "$#" = "1" ];then
		if [ "$1" = "cancelar" ];then
			mostrar_grabar "Proceso de instalación cancelado" I
		fi
	fi
	#*******Se elimina la carpeta de archivos temporales y se corta la ejecución de InstalarC
	rm -fr $GRUPO/temp
	exit 0
}

#*******Muestra un mensaje por pantalla, y lo guarda en el log de InstalarC
function mostrar_grabar
{	
	#Obligatorios
	#$1 mensaje
	#$2 tipo de mensaje
	#Opcional
	#$3 si se muestra o logea unicamente

	#si no se pasa $3, se muestra por pantalla y se loguea. Si $3=G el mensaje solo se loguea, si viene con otro valor 		#distinto, solo se muestra por pantalla
	if [ "$#" = 3 ];then
		if [ "$3" = "G" ];then
			"$LIBDIR"/loguearC "InstalarC" "$2" "$1"
		else
			echo -e "$1"
		fi
	else	
		"$LIBDIR"/loguearC "InstalarC" "$2" "$1"
		echo -e "$1"
	fi
}

#*******Instala solo los componentes faltantes, y segun los parametros de instalacion del InstalarC.conf existente
function instalacion_parcial
{
	#*******Se pregunta si se acepta la instalacion parcial, y se muestran los parametros de instalacion existentes
	mostrar_grabar "Se propone la instalación de los componentes faltantes, con las variables de instalación" I
	mostrar_grabar "siguientes, predefinidas en el archivo de configuración : " I
	AUXCAT=$(cat "$GRUPO/conf/InstalarC.conf")
	mostrar_grabar "$AUXCAT" I
	mostrar_grabar "¿acepta completar la instalación?(Si/No)" I
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	RESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")		
	if [ "$RESPUESTA" = "SI" ];then
		#*******levanta los parametros de instalacion de InstalarC.conf, y crea los ejecutables faltantes
		setParamFromConf
		generar_directorios_archivos
		actualizar_archivo_configuracion
		#*******se verifica nuevamente la instalacion, para generar los mensajes de componentes instalados y no 		#*******instalados, y se imprime el mensaje final de como termino la instalacion parcial		
		verificar_instalacion
		print_instalacion_parcial
		mostrar_grabar "* FIN del proceso de Instalación Copyright SisOp (c)2011	*" I
		mostrar_grabar "*****************************************************************" I
	else
		#*******se da la opcion de iniciar una instalacion completa de cero en caso de no querer la parcial
		mostrar_grabar "¿desea iniciar una instalación completa nueva?(Si/No)" I
		read -e RESPUESTA	
		mostrar_grabar "$RESPUESTA" I G
		RESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")		
		if [ "$RESPUESTA" = "SI" ];then
			#*******se setean todos los componentes como no instalados, y se setean los parametros de 				#*******instalacion default, ignorando el InstalarC.conf existente
			INSTALADOS[1]="NO"
			INSTALADOS[2]="NO"
			INSTALADOS[3]="NO"
			INSTALADOS[4]="NO"
			setParamDefault
			instalacion_completa
		else
			#*******en caso de no querer instalacion parcial o completa se cancela la ejecución
			fin "cancelar"
		fi	
	fi
}

#*******Instala todos los componentes, previo seteo de los parametros de configuracion por parte del usuario 
function instalacion_completa
{		
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*      Sistema Consultar Copyright SisOp (c)2011       *' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*Al instalar Consultar UD. expresa estar en un todo de acuerdo *' I
	mostrar_grabar '*con los términos y condiciones del \"ACUERDO DE LICENCIA DE *' I
	mostrar_grabar '*SOFTWARE \" incluido en este paquete.' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar 'Aceptar/Rechazar(a/r)' I
	RESPUESTA="";	
	read -e RESPUESTA
	mostrar_grabar "$RESPUESTA" I G
	unificar_respuestas
	if [ "$RESPUESTA" = "a" ];then	
		#*******Chequea si se posee una version 5 o superior de Perl, y se abandona la instalacion de no tenerse 
		PERL=$(perl --version | sed -n "s/\(.*v\)\([5-9]\.[0-9.]*\)\(.*\)/\2/p")	
		if [ "$PERL" = "" ];then
			mostrar_grabar "Para instalar Consultar es necesario contar con Perl 5 o superior" I
			mostrar_grabar "intalado. Efectúe su instalación e inténtelo nuevamente. Proceso de" I
			mostrar_grabar "Instalación Cancelado" I
		else
			#*******se informa la version de perl que se posee y se brinda informacion sobre donde se va hacer 				#*******la instalación y sobre la misma en general
			mostrar_grabar "La version de perl instalada en el sistema es v$PERL" I
			mostrar_grabar "Todos los directorios del sistema serán subdirectorios de $GRUPO" I
			mostrar_grabar "Todos los componentes de la instalación se obtendrán del repositorio:" I
			mostrar_grabar "$GRUPO/inst" I
			#*******se listan los archivos existentes en la carpeta inst por pantalla
			AUXLISTADO=$(ls "$GRUPO/inst")			
			mostrar_grabar "$AUXLISTADO" I
			mostrar_grabar "El log de la instalacion se almacenara en $GRUPO/inst" I
			mostrar_grabar "Al finalizar la instalación, si la misma fue exitosa se dejara un" I
 			mostrar_grabar "archivo de configuración en $GRUPO/conf" I
			while [ "1" = "1" ]; do
				#*******empieza la etapa de seteo de parametros de instalación por parte del usuario
				configurar_instalacion
				#*******si se llega a esta instancia es porque no hubo cancelacion en la etapa de 					#*******configuración, por lo que se salio de la misma exitosamente, y se muestra los 					#*******valores seteados que se van a guardar en InstalarC.conf
				clear
				mostrar_grabar  "****************************************************************" I
				mostrar_grabar  "*" I
				mostrar_grabar  "*	Parámetros de instalación del paquete Consultar		*" I
				mostrar_grabar  "****************************************************************" I
				mostrar_grabar  "*" I
				mostrar_grabar  "Directorio de trabajo: $GRUPO" I
				mostrar_grabar  "Directorio de instalación: $GRUPO/inst" I
				mostrar_grabar  "Directorio de configuración: $GRUPO/conf" I
				mostrar_grabar  "Directorio de datos maestros: $GRUPO/mae" I
				mostrar_grabar  "Directorio de ejecutables: $DEFBINDIR" I
				mostrar_grabar  "Librería de funciones: $GRUPO/lib" I
				mostrar_grabar	"Directorio de arribos: $DEFARRIDIR" I
				mostrar_grabar	"Espacio mínimo reservado en $ARRIDIR: $DEFDATASIZE MB" I
				mostrar_grabar  "Directorio para los archivos de Log: $DEFLOGDIR" I
				mostrar_grabar  "Extensión para los archivos de Log: $DEFLOGEXT" I
				mostrar_grabar  "Tamaño máximo para los archivos de Log: $DEFLOGSIZE KB" I
				mostrar_grabar  "Log de la instalación: $GRUPO/inst" I
				mostrar_grabar  "Si los datos ingresados son correctos de ENTER para continuar, si" I
				mostrar_grabar	"desea modificar algún parámetro oprima cualquier tecla para reiniciar" I
				#*******se lee un caracter ingresado por teclado, y si el mismo es '', se presiono enter.
				read -d '' -sn1 RESPUESTA
				if [ "$RESPUESTA" = "" ];then
					#*******el usuario acepta los valores seteados, y continua la instalación
					mostrar_grabar "se presiono enter" I G
					break
				else
					#*******el usuario desea modificar algun valor, por lo que se vuelve al comienzo 						#*******del while, para empezar nuevamente el seteo de parametros
					mostrar_grabar "$RESPUESTA" I G					
					clear
				fi
			done
			mostrar_grabar "Iniciando Instalación... Está UD. seguro? (Si/No)" I	
			#*******Se pide confirmación de instalación, cancelando la misma en caso negativo		
			read -e RESPUESTA	
			mostrar_grabar "$RESPUESTA" I G
			RESPUESTA=$(echo $RESPUESTA | tr "[:lower:]" "[:upper:]")		
			if [ "$RESPUESTA" != "SI" ];then
				fin "cancelar"
			fi
			#*******se generan los directorios y archivos segun los parametros seteados y se actualiza el 				#*******archivo de configuracion InstalarC.conf
			generar_directorios_archivos
			actualizar_archivo_configuracion
			#*******se verifica la instalación para generar nuevamente los mensajes de componentes instalados 				#*******y faltantes, y se imprime el mensaje final de como termino la instalación 
			verificar_instalacion
			print_instalacion_parcial
			mostrar_grabar "* FIN del proceso de Instalación Copyright SisOp (c)2011	*" I
			mostrar_grabar "*****************************************************************" I	
		fi
	else
		fin "cancelar"
	fi
}

#*******Imprime por pantalla que hay una instalación completa
function print_instalacion_completa
{
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*      Sistema Consultar Copyright SisOp (c)2011       *' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*Se encuentran instalados los siguientes componentes:  *' I
	mostrar_grabar "$MENSAJESI" I
	mostrar_grabar '********************************************************' I
	mostrar_grabar 'Proceso de instalacion cancelado' I
}

#*******Imprime por pantalla, que componentes hay instalados y cuales faltan por instalar
function print_instalacion_parcial
{
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*      Sistema Consultar Copyright SisOp (c)2011       *' I
	mostrar_grabar '********************************************************' I
	mostrar_grabar '*Se encuentran instalados los siguientes componentes:  *' I
	mostrar_grabar "$MENSAJESI" I
	mostrar_grabar '*Falta instalar los siguientes componentes:            *' I
	mostrar_grabar "$MENSAJENO" I
	mostrar_grabar '********************************************************' I
}

#*******Verifica si un determinado comando ya esta instalado.
function comando_instalado
{
#*******$1 path del comando cuya existencia hay que verificar
#*******$2 nombre del comando
#*******$3 indice del comando en el arreglo de Instalados
#*******INSTALACION se asigna el estado de la instalación, completa, parcial o ninguna
	if [ -f $1 ];then
		OWNER=$(stat -c %U "$1")
		FECHACREACION=$(date -r $1 "+%d/%m/%Y %k:%M:%S")
		INSTALADOS[$3]="SI"
		MENSAJESI="$MENSAJESI\n*$2 $FECHACREACION $OWNER*"
	else
		INSTALACION="parcial"
		INSTALADOS[$3]="NO"
		MENSAJENO="$MENSAJENO\n*$2"
	fi 
}

#*******verifica si el paquete Consulta se encuentra instalado y en que forma se encuentra instalado, retornando dicha #*******informacion a traves de las variables INSTALACION e INSTALADOS
function verificar_instalacion
{ 
#1iniciarC
#2detectarC
#3sumarC
#4listarC
FILE="$GRUPO/conf/InstalarC.conf"
INSTALADOS[1]="NO"
INSTALADOS[2]="NO"
INSTALADOS[3]="NO"
INSTALADOS[4]="NO"
#*******se verifica que exista el archivo de configuración InstalarC.conf, obligatorio si hubo una instalación previa
if [ -f $FILE ];then
	INSTALACION="completa"
	MENSAJESI=""
	MENSAJENO=""
	#se verifica que esten instalados los comandos en el bindir obtenido de InstalarC.conf
	getConfigParam "BINDIR"
	PATHAUX="$GRUPO$CONFIGPARAM/iniciarC"
	comando_instalado $PATHAUX "iniciarC" 1
	PATHAUX="$GRUPO$CONFIGPARAM/detectarC"
	comando_instalado $PATHAUX "detectarC"	2
	PATHAUX="$GRUPO$CONFIGPARAM/sumarC"
	comando_instalado $PATHAUX "sumarC" 3	
	PATHAUX="$GRUPO$CONFIGPARAM/listarC"
	comando_instalado $PATHAUX "listarC" 4	
	if [ "$MENSAJESI" = "" ];then
		INSTALACION="ninguna"
	fi

else 
	INSTALACION="ninguna"
fi
}
function getConfigParam
{
	CONFIGPARAM=$(sed -n "s/$1 = //p" $GRUPO/conf/InstalarC.conf)
}

#**************************************Comienza el cuerpo del InstalarC****************************************************
GRUPO=$(pwd)
GRUPO="$GRUPO/$0"
GRUPO=$(echo $GRUPO | sed -n "s/\(.*\)\(\/inst\/.*\)/\1/p")
LIBDIR="$GRUPO/lib"
#*******Se crea la carpeta donde van a estar los archivos temporales a usar
mkdir -p $GRUPO/temp
#*******Se hacen los preparativos para usar loguearC
#*******Se cargan y exportan las variables requeridas por loguearC
PATH=${PATH}:$LIBDIR
DATAMAE=$GRUPO/temp
export GRUPO
export LOGSIZE=400000
export LOGEXT=log
export LOGDIR="$GRUPO/inst"
export PATH
export DATAMAE
#*******Se setean los permisos de las librerias
chmod 777 "$LIBDIR"/*

#*******Se copia el archivo errores.mae a temp, para uso de manera temporal por loguearC 
if [ -f "$GRUPO/inst/errores.mae" ];then
	cp "$GRUPO/inst/errores.mae" "$GRUPO/temp/errores.mae"		
else
	mostrar_grabar "Error en la instalacion, no se puede encontrar el archivo errores.mae original. Instalación corrompida, consulte a su proveedor" I
	fin "cancelar"
fi

#*******fin preparativos para uso del loguear

#*******se evalúan si los parametros que llegan, lo hacen de manera valida
if [ $# -gt 1 ]
then
    mostrar_grabar "Cantidad erronea de parametros, se requieren a lo sumo 1" ES
    fin "cancelar"
fi

if [ $# -eq 1 ];then
	if [ $1 = '--help' -o $1 = "-h" ]
	then
	    mostrarAyuda    
	    fin
	fi
	if [ $1 = "--version" -o $1 = "-v" ]
	then
    		echo
   		echo "InstalarC v 1.0"
    		echo "Escrito por Flavio Ferro"
   		echo
    		fin
	fi
	mostrar_grabar "el parametro ingresado es erroneo, ejecute InstalarC --help para obtener ayuda" ES
	fin "cancelar"	
fi 
#*******en caso de no haber parametro alguno, arranca la ejecucion del InstalarC propiamente dicha
DATE=$(date "+%d/%m/%Y %k:%M:%S")
mostrar_grabar "$DATE-$USERNAME-instalarC-I-Inicio de ejecucion" I G
#*******se verifica si esta instalado el paquete consulta, para determinar si es necesario instalar, y en que forma, si #*******total o parcial
verificar_instalacion
case "$INSTALACION" in
	"completa")
		print_instalacion_completa
		;;
	"parcial")
		print_instalacion_parcial
		instalacion_parcial
		;;
	"ninguna")
		if [ -f $GRUPO/conf/InstalarC.conf ];then
			setParamFromConf	
		else
			setParamDefault
		fi
		instalacion_completa
		;;
esac
fin

